# Generated by Django 2.1.3 on 2019-02-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190201_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user.png', upload_to='profile_pic/'),
        ),
    ]
