# Generated by Django 2.1.3 on 2019-01-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190116_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='discription',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='mission',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='outcomes',
            field=models.TextField(max_length=300),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Curriculum', to='courses.Course'),
        ),
    ]
