# Generated by Django 2.1.3 on 2019-01-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190119_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='isfree',
        ),
    ]
