# Generated by Django 2.1.3 on 2019-01-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190120_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='video'),
        ),
    ]
