# Generated by Django 2.1.3 on 2019-01-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190120_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='attachments',
            field=models.FileField(null=True, upload_to='attachments/', verbose_name='attachments'),
        ),
    ]
