# Generated by Django 2.1.3 on 2019-01-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lecture_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='discription',
        ),
    ]
